---
language: node_js
node_js:
  - "4"

sudo: false

branches:
  only:
    - master

cache:
  directories:
    - node_modules

env:
  global:
    - PERCY_PROJECT=kellyselden/package-hint-historic-resolver
    - PERCY_PARALLEL_TOTAL=5
  matrix:
    - PARTITION=1
    - PARTITION=2
    - PARTITION=3
    - PARTITION=4
    - PARTITION=5

before_install:
  - npm config set spin false
  - npm install -g bower
  - npm install phantomjs-prebuilt

install:
  - npm install
  - bower install

script:
  - ./scripts/travis.sh

after_script:
  - cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
